### ISSUE TITLE
Project Burnout --> Maintainer Wellness

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-dei#399]
Hi everyone, 

There is a recommendation from the metrics-model WG to rename the project burnout metric to maintainer wellness.

**Comment by Nebrethar** [comment]
I'm a little worried the differentiation between [Project Burnout->Maintainer Wellness](https://github.com/chaoss/wg-dei/blob/main/focus-areas/project-and-community/project-burnout.md) and [Psychological Safety](https://github.com/chaoss/wg-dei/blob/main/focus-areas/project-and-community/psychological-safety.md) will be blurred.

**Comment by LawrenceHecht** [comment]
IMHO, project burnout has nothing to do with Psychological Safety. It has to do with 

1. level of exhaustion
2. feeling valued
3. what someone is going to do about these feelings

In this regard, Project Burnout and Psychological Safety are just two components of Maintainer Wellness.

**Comment by emmairwin** [comment]
I agree with @LawrenceHecht but I think what the proposal is, is not that project burn out is ONLY wellness, but rather that currently what we have defined as [project burnout ](https://chaoss.community/metric-project-burnout/) iss  **is only about wellness** , and that this should be renamed for that reason.  That renaming this gives room for those other attributes of burnout which Elizabeth and I brainstormed in this doc:

https://docs.google.com/document/d/1iCO987aeO75oYzpOPY7KhqCsRBfqwn5eiKNAOz5tZoY/edit

**Comment by ElizabethN** [comment]
Based on input from the community during the DEI Working Group call and various Slack conversations, we will keep the name as it is for a few reasons:
- "Maintainer Wellness" is a very broad term, and framing it with this lens might lead some to think we have expertise in mental health. We do not. 
- Full "Maintainer Wellness" is something it would be difficult to measure through this metric, as there could be external factors that affect a person's wellness that have nothing to do with the project. 
- "Maintainer" wellness only focuses on one subset of the community (maintainers).
- This metric is really about how the Project culture and support systems are set up to measure and track burnout, so because the metric is project-focused, we should keep the name project-focused. 

Although we are going to close this discussion, this has been a long-running conversation, and if anyone in the community would like to revisit this again in the future, they should feel empowered to do so.
